// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: works.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Works_ListWorks_FullMethodName    = "/stream.Works/ListWorks"
	Works_CreatedWorks_FullMethodName = "/stream.Works/CreatedWorks"
	Works_DeleteWorks_FullMethodName  = "/stream.Works/DeleteWorks"
	Works_InfoWorks_FullMethodName    = "/stream.Works/InfoWorks"
	Works_UpdateWorks_FullMethodName  = "/stream.Works/UpdateWorks"
)

// WorksClient is the client API for Works service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorksClient interface {
	ListWorks(ctx context.Context, in *ListWorksReq, opts ...grpc.CallOption) (*ListWorksResp, error)
	CreatedWorks(ctx context.Context, in *CreatedWorksReq, opts ...grpc.CallOption) (*CreatedWorksResp, error)
	DeleteWorks(ctx context.Context, in *DeleteWorksReq, opts ...grpc.CallOption) (*DeleteWorksResp, error)
	InfoWorks(ctx context.Context, in *InfoWorksReq, opts ...grpc.CallOption) (*InfoWorksResp, error)
	UpdateWorks(ctx context.Context, in *UpdateWorksReq, opts ...grpc.CallOption) (*UpdateWorksResp, error)
}

type worksClient struct {
	cc grpc.ClientConnInterface
}

func NewWorksClient(cc grpc.ClientConnInterface) WorksClient {
	return &worksClient{cc}
}

func (c *worksClient) ListWorks(ctx context.Context, in *ListWorksReq, opts ...grpc.CallOption) (*ListWorksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorksResp)
	err := c.cc.Invoke(ctx, Works_ListWorks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksClient) CreatedWorks(ctx context.Context, in *CreatedWorksReq, opts ...grpc.CallOption) (*CreatedWorksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatedWorksResp)
	err := c.cc.Invoke(ctx, Works_CreatedWorks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksClient) DeleteWorks(ctx context.Context, in *DeleteWorksReq, opts ...grpc.CallOption) (*DeleteWorksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorksResp)
	err := c.cc.Invoke(ctx, Works_DeleteWorks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksClient) InfoWorks(ctx context.Context, in *InfoWorksReq, opts ...grpc.CallOption) (*InfoWorksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoWorksResp)
	err := c.cc.Invoke(ctx, Works_InfoWorks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksClient) UpdateWorks(ctx context.Context, in *UpdateWorksReq, opts ...grpc.CallOption) (*UpdateWorksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorksResp)
	err := c.cc.Invoke(ctx, Works_UpdateWorks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorksServer is the server API for Works service.
// All implementations must embed UnimplementedWorksServer
// for forward compatibility
type WorksServer interface {
	ListWorks(context.Context, *ListWorksReq) (*ListWorksResp, error)
	CreatedWorks(context.Context, *CreatedWorksReq) (*CreatedWorksResp, error)
	DeleteWorks(context.Context, *DeleteWorksReq) (*DeleteWorksResp, error)
	InfoWorks(context.Context, *InfoWorksReq) (*InfoWorksResp, error)
	UpdateWorks(context.Context, *UpdateWorksReq) (*UpdateWorksResp, error)
	mustEmbedUnimplementedWorksServer()
}

// UnimplementedWorksServer must be embedded to have forward compatible implementations.
type UnimplementedWorksServer struct {
}

func (UnimplementedWorksServer) ListWorks(context.Context, *ListWorksReq) (*ListWorksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorks not implemented")
}
func (UnimplementedWorksServer) CreatedWorks(context.Context, *CreatedWorksReq) (*CreatedWorksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatedWorks not implemented")
}
func (UnimplementedWorksServer) DeleteWorks(context.Context, *DeleteWorksReq) (*DeleteWorksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorks not implemented")
}
func (UnimplementedWorksServer) InfoWorks(context.Context, *InfoWorksReq) (*InfoWorksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InfoWorks not implemented")
}
func (UnimplementedWorksServer) UpdateWorks(context.Context, *UpdateWorksReq) (*UpdateWorksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorks not implemented")
}
func (UnimplementedWorksServer) mustEmbedUnimplementedWorksServer() {}

// UnsafeWorksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorksServer will
// result in compilation errors.
type UnsafeWorksServer interface {
	mustEmbedUnimplementedWorksServer()
}

func RegisterWorksServer(s grpc.ServiceRegistrar, srv WorksServer) {
	s.RegisterService(&Works_ServiceDesc, srv)
}

func _Works_ListWorks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorksServer).ListWorks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Works_ListWorks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorksServer).ListWorks(ctx, req.(*ListWorksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Works_CreatedWorks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatedWorksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorksServer).CreatedWorks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Works_CreatedWorks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorksServer).CreatedWorks(ctx, req.(*CreatedWorksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Works_DeleteWorks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorksServer).DeleteWorks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Works_DeleteWorks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorksServer).DeleteWorks(ctx, req.(*DeleteWorksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Works_InfoWorks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoWorksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorksServer).InfoWorks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Works_InfoWorks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorksServer).InfoWorks(ctx, req.(*InfoWorksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Works_UpdateWorks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorksServer).UpdateWorks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Works_UpdateWorks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorksServer).UpdateWorks(ctx, req.(*UpdateWorksReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Works_ServiceDesc is the grpc.ServiceDesc for Works service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Works_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.Works",
	HandlerType: (*WorksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWorks",
			Handler:    _Works_ListWorks_Handler,
		},
		{
			MethodName: "CreatedWorks",
			Handler:    _Works_CreatedWorks_Handler,
		},
		{
			MethodName: "DeleteWorks",
			Handler:    _Works_DeleteWorks_Handler,
		},
		{
			MethodName: "InfoWorks",
			Handler:    _Works_InfoWorks_Handler,
		},
		{
			MethodName: "UpdateWorks",
			Handler:    _Works_UpdateWorks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "works.proto",
}
